[package]
name = "screen-toggle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.25"
futures-signals = "0.3.31"
rdev = "0.5.2"
tokio = { version = "1.24.2", features = ["full"] }
